<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        App\Country::create(['name' => 'Afganistán', 'english_name' => 'Afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'phone_prefix' => '93']);
        App\Country::create(['name' => 'Albania', 'english_name' => 'Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'phone_prefix' => '355']);
        App\Country::create(['name' => 'Alemania', 'english_name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'phone_prefix' => '49']);
        App\Country::create(['name' => 'Algeria', 'english_name' => 'Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'phone_prefix' => '213']);
        App\Country::create(['name' => 'Andorra', 'english_name' => 'Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'phone_prefix' => '376']);
        App\Country::create(['name' => 'Angola', 'english_name' => 'Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'phone_prefix' => '244']);
        App\Country::create(['name' => 'Anguila', 'english_name' => 'Anguilla', 'iso2' => 'AI', 'iso3' => 'AIA', 'phone_prefix' => '1 264']);
        App\Country::create(['name' => 'Antártida', 'english_name' => 'Antarctica', 'iso2' => 'AQ', 'iso3' => 'ATA', 'phone_prefix' => '672']);
        App\Country::create(['name' => 'Antigua y Barbuda', 'english_name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'phone_prefix' => '1 268']);
        App\Country::create(['name' => 'Antillas Neerlandesas', 'english_name' => 'Netherlands Antilles', 'iso2' => 'AN', 'iso3' => 'ANT', 'phone_prefix' => '599']);
        App\Country::create(['name' => 'Arabia Saudita', 'english_name' => 'Saudi Arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'phone_prefix' => '966']);
        App\Country::create(['name' => 'Argentina', 'english_name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'phone_prefix' => '54']);
        App\Country::create(['name' => 'Armenia', 'english_name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'phone_prefix' => '374']);
        App\Country::create(['name' => 'Aruba', 'english_name' => 'Aruba', 'iso2' => 'AW', 'iso3' => 'ABW', 'phone_prefix' => '297']);
        App\Country::create(['name' => 'Australia', 'english_name' => 'Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'phone_prefix' => '61']);
        App\Country::create(['name' => 'Austria', 'english_name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'phone_prefix' => '43']);
        App\Country::create(['name' => 'Azerbayán', 'english_name' => 'Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'phone_prefix' => '994']);
        App\Country::create(['name' => 'Bélgica', 'english_name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'phone_prefix' => '32']);
        App\Country::create(['name' => 'Bahamas', 'english_name' => 'Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'phone_prefix' => '1 242']);
        App\Country::create(['name' => 'Bahrein', 'english_name' => 'Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'phone_prefix' => '973']);
        App\Country::create(['name' => 'Bangladesh', 'english_name' => 'Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'phone_prefix' => '880']);
        App\Country::create(['name' => 'Barbados', 'english_name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'phone_prefix' => '1 246']);
        App\Country::create(['name' => 'Belice', 'english_name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'phone_prefix' => '501']);
        App\Country::create(['name' => 'Benín', 'english_name' => 'Benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'phone_prefix' => '229']);
        App\Country::create(['name' => 'Bhután', 'english_name' => 'Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'phone_prefix' => '975']);
        App\Country::create(['name' => 'Bielorrusia', 'english_name' => 'Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'phone_prefix' => '375']);
        App\Country::create(['name' => 'Birmania', 'english_name' => 'Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'phone_prefix' => '95']);
        App\Country::create(['name' => 'Bolivia', 'english_name' => 'Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'phone_prefix' => '591']);
        App\Country::create(['name' => 'Bosnia y Herzegovina', 'english_name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'phone_prefix' => '387']);
        App\Country::create(['name' => 'Botsuana', 'english_name' => 'Botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'phone_prefix' => '267']);
        App\Country::create(['name' => 'Brasil', 'english_name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'phone_prefix' => '55']);
        App\Country::create(['name' => 'Brunéi', 'english_name' => 'Brunei', 'iso2' => 'BN', 'iso3' => 'BRN', 'phone_prefix' => '673']);
        App\Country::create(['name' => 'Bulgaria', 'english_name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'phone_prefix' => '359']);
        App\Country::create(['name' => 'Burkina Faso', 'english_name' => 'Burkina Faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'phone_prefix' => '226']);
        App\Country::create(['name' => 'Burundi', 'english_name' => 'Burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'phone_prefix' => '257']);
        App\Country::create(['name' => 'Cabo Verde', 'english_name' => 'Cape Verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'phone_prefix' => '238']);
        App\Country::create(['name' => 'Camboya', 'english_name' => 'Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'phone_prefix' => '855']);
        App\Country::create(['name' => 'Camerún', 'english_name' => 'Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'phone_prefix' => '237']);
        App\Country::create(['name' => 'Canadá', 'english_name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'phone_prefix' => '1']);
        App\Country::create(['name' => 'Chad', 'english_name' => 'Chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'phone_prefix' => '235']);
        App\Country::create(['name' => 'Chile', 'english_name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'phone_prefix' => '56']);
        App\Country::create(['name' => 'China', 'english_name' => 'China', 'iso2' => 'CN', 'iso3' => 'CHN', 'phone_prefix' => '86']);
        App\Country::create(['name' => 'Chipre', 'english_name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'phone_prefix' => '357']);
        App\Country::create(['name' => 'Ciudad del Vaticano', 'english_name' => 'Vatican City State', 'iso2' => 'VA', 'iso3' => 'VAT', 'phone_prefix' => '39']);
        App\Country::create(['name' => 'Colombia', 'english_name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'phone_prefix' => '57']);
        App\Country::create(['name' => 'Comoras', 'english_name' => 'Comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'phone_prefix' => '269']);
        App\Country::create(['name' => 'Congo', 'english_name' => 'Congo', 'iso2' => 'CG', 'iso3' => 'COG', 'phone_prefix' => '242']);
        App\Country::create(['name' => 'Congo', 'english_name' => 'Congo', 'iso2' => 'CD', 'iso3' => 'COD', 'phone_prefix' => '243']);
        App\Country::create(['name' => 'Corea del Norte', 'english_name' => 'North Korea', 'iso2' => 'KP', 'iso3' => 'PRK', 'phone_prefix' => '850']);
        App\Country::create(['name' => 'Corea del Sur', 'english_name' => 'South Korea', 'iso2' => 'KR', 'iso3' => 'KOR', 'phone_prefix' => '82']);
        App\Country::create(['name' => 'Costa de Marfil', 'english_name' => 'Ivory Coast', 'iso2' => 'CI', 'iso3' => 'CIV', 'phone_prefix' => '225']);
        App\Country::create(['name' => 'Costa Rica', 'english_name' => 'Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'phone_prefix' => '506']);
        App\Country::create(['name' => 'Croacia', 'english_name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'phone_prefix' => '385']);
        App\Country::create(['name' => 'Cuba', 'english_name' => 'Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'phone_prefix' => '53']);
        App\Country::create(['name' => 'Dinamarca', 'english_name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'phone_prefix' => '45']);
        App\Country::create(['name' => 'Dominica', 'english_name' => 'Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'phone_prefix' => '1 767']);
        App\Country::create(['name' => 'Ecuador', 'english_name' => 'Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'phone_prefix' => '593']);
        App\Country::create(['name' => 'Egipto', 'english_name' => 'Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'phone_prefix' => '20']);
        App\Country::create(['name' => 'El Salvador', 'english_name' => 'El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'phone_prefix' => '503']);
        App\Country::create(['name' => 'Emiratos Árabes Unidos', 'english_name' => 'United Arab Emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'phone_prefix' => '971']);
        App\Country::create(['name' => 'Eritrea', 'english_name' => 'Eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'phone_prefix' => '291']);
        App\Country::create(['name' => 'Eslovaquia', 'english_name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'phone_prefix' => '421']);
        App\Country::create(['name' => 'Eslovenia', 'english_name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'phone_prefix' => '386']);
        App\Country::create(['name' => 'España', 'english_name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'phone_prefix' => '34']);
        App\Country::create(['name' => 'Estados Unidos de América', 'english_name' => 'United States of America', 'iso2' => 'US', 'iso3' => 'USA', 'phone_prefix' => '1']);
        App\Country::create(['name' => 'Estonia', 'english_name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'phone_prefix' => '372']);
        App\Country::create(['name' => 'Etiopía', 'english_name' => 'Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'phone_prefix' => '251']);
        App\Country::create(['name' => 'Filipinas', 'english_name' => 'Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'phone_prefix' => '63']);
        App\Country::create(['name' => 'Finlandia', 'english_name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'phone_prefix' => '358']);
        App\Country::create(['name' => 'Fiyi', 'english_name' => 'Fiji', 'iso2' => 'FJ', 'iso3' => 'FJI', 'phone_prefix' => '679']);
        App\Country::create(['name' => 'Francia', 'english_name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'phone_prefix' => '33']);
        App\Country::create(['name' => 'Gabón', 'english_name' => 'Gabon', 'iso2' => 'GA', 'iso3' => 'GAB', 'phone_prefix' => '241']);
        App\Country::create(['name' => 'Gambia', 'english_name' => 'Gambia', 'iso2' => 'GM', 'iso3' => 'GMB', 'phone_prefix' => '220']);
        App\Country::create(['name' => 'Georgia', 'english_name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'phone_prefix' => '995']);
        App\Country::create(['name' => 'Ghana', 'english_name' => 'Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'phone_prefix' => '233']);
        App\Country::create(['name' => 'Gibraltar', 'english_name' => 'Gibraltar', 'iso2' => 'GI', 'iso3' => 'GIB', 'phone_prefix' => '350']);
        App\Country::create(['name' => 'Granada', 'english_name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'phone_prefix' => '1 473']);
        App\Country::create(['name' => 'Grecia', 'english_name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'phone_prefix' => '30']);
        App\Country::create(['name' => 'Groenlandia', 'english_name' => 'Greenland', 'iso2' => 'GL', 'iso3' => 'GRL', 'phone_prefix' => '299']);
        App\Country::create(['name' => 'Guadalupe', 'english_name' => 'Guadeloupe', 'iso2' => 'GP', 'iso3' => 'GLP', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Guam', 'english_name' => 'Guam', 'iso2' => 'GU', 'iso3' => 'GUM', 'phone_prefix' => '1 671']);
        App\Country::create(['name' => 'Guatemala', 'english_name' => 'Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'phone_prefix' => '502']);
        App\Country::create(['name' => 'Guayana Francesa', 'english_name' => 'French Guiana', 'iso2' => 'GF', 'iso3' => 'GUF', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Guernsey', 'english_name' => 'Guernsey', 'iso2' => 'GG', 'iso3' => 'GGY', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Guinea', 'english_name' => 'Guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'phone_prefix' => '224']);
        App\Country::create(['name' => 'Guinea Ecuatorial', 'english_name' => 'Equatorial Guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'phone_prefix' => '240']);
        App\Country::create(['name' => 'Guinea-Bissau', 'english_name' => 'Guinea-Bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'phone_prefix' => '245']);
        App\Country::create(['name' => 'Guyana', 'english_name' => 'Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'phone_prefix' => '592']);
        App\Country::create(['name' => 'Haití', 'english_name' => 'Haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'phone_prefix' => '509']);
        App\Country::create(['name' => 'Honduras', 'english_name' => 'Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'phone_prefix' => '504']);
        App\Country::create(['name' => 'Hong kong', 'english_name' => 'Hong Kong', 'iso2' => 'HK', 'iso3' => 'HKG', 'phone_prefix' => '852']);
        App\Country::create(['name' => 'Hungría', 'english_name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'phone_prefix' => '36']);
        App\Country::create(['name' => 'India', 'english_name' => 'India', 'iso2' => 'IN', 'iso3' => 'IND', 'phone_prefix' => '91']);
        App\Country::create(['name' => 'Indonesia', 'english_name' => 'Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'phone_prefix' => '62']);
        App\Country::create(['name' => 'Irán', 'english_name' => 'Iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'phone_prefix' => '98']);
        App\Country::create(['name' => 'Irak', 'english_name' => 'Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'phone_prefix' => '964']);
        App\Country::create(['name' => 'Irlanda', 'english_name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'phone_prefix' => '353']);
        App\Country::create(['name' => 'Isla Bouvet', 'english_name' => 'Bouvet Island', 'iso2' => 'BV', 'iso3' => 'BVT', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Isla de Man', 'english_name' => 'Isle of Man', 'iso2' => 'IM', 'iso3' => 'IMN', 'phone_prefix' => '44']);
        App\Country::create(['name' => 'Isla de Navidad', 'english_name' => 'Christmas Island', 'iso2' => 'CX', 'iso3' => 'CXR', 'phone_prefix' => '61']);
        App\Country::create(['name' => 'Isla Norfolk', 'english_name' => 'Norfolk Island', 'iso2' => 'NF', 'iso3' => 'NFK', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Islandia', 'english_name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'phone_prefix' => '354']);
        App\Country::create(['name' => 'Islas Bermudas', 'english_name' => 'Bermuda Islands', 'iso2' => 'BM', 'iso3' => 'BMU', 'phone_prefix' => '1 441']);
        App\Country::create(['name' => 'Islas Caimán', 'english_name' => 'Cayman Islands', 'iso2' => 'KY', 'iso3' => 'CYM', 'phone_prefix' => '1 345']);
        App\Country::create(['name' => 'Islas Cocos (Keeling)', 'english_name' => 'Cocos (Keeling) Islands', 'iso2' => 'CC', 'iso3' => 'CCK', 'phone_prefix' => '61']);
        App\Country::create(['name' => 'Islas Cook', 'english_name' => 'Cook Islands', 'iso2' => 'CK', 'iso3' => 'COK', 'phone_prefix' => '682']);
        App\Country::create(['name' => 'Islas de Åland', 'english_name' => 'Åland Islands', 'iso2' => 'AX', 'iso3' => 'ALA', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Islas Feroe', 'english_name' => 'Faroe Islands', 'iso2' => 'FO', 'iso3' => 'FRO', 'phone_prefix' => '298']);
        App\Country::create(['name' => 'Islas Georgias del Sur y Sandwich del Sur', 'english_name' => 'South Georgia and the South Sandwich Islands', 'iso2' => 'GS', 'iso3' => 'SGS', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Islas Heard y McDonald', 'english_name' => 'Heard Island and McDonald Islands', 'iso2' => 'HM', 'iso3' => 'HMD', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Islas Maldivas', 'english_name' => 'Maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'phone_prefix' => '960']);
        App\Country::create(['name' => 'Islas Malvinas', 'english_name' => 'Falkland Islands (Malvinas)', 'iso2' => 'FK', 'iso3' => 'FLK', 'phone_prefix' => '500']);
        App\Country::create(['name' => 'Islas Marianas del Norte', 'english_name' => 'Northern Mariana Islands', 'iso2' => 'MP', 'iso3' => 'MNP', 'phone_prefix' => '1 670']);
        App\Country::create(['name' => 'Islas Marshall', 'english_name' => 'Marshall Islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'phone_prefix' => '692']);
        App\Country::create(['name' => 'Islas Pitcairn', 'english_name' => 'Pitcairn Islands', 'iso2' => 'PN', 'iso3' => 'PCN', 'phone_prefix' => '870']);
        App\Country::create(['name' => 'Islas Salomón', 'english_name' => 'Solomon Islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'phone_prefix' => '677']);
        App\Country::create(['name' => 'Islas Turcas y Caicos', 'english_name' => 'Turks and Caicos Islands', 'iso2' => 'TC', 'iso3' => 'TCA', 'phone_prefix' => '1 649']);
        App\Country::create(['name' => 'Islas Ultramarinas Menores de Estados Unidos', 'english_name' => 'United States Minor Outlying Islands', 'iso2' => 'UM', 'iso3' => 'UMI', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Islas Vírgenes Británicas', 'english_name' => 'Virgin Islands', 'iso2' => 'VG', 'iso3' => 'VG', 'phone_prefix' => '1 284']);
        App\Country::create(['name' => 'Islas Vírgenes de los Estados Unidos', 'english_name' => 'United States Virgin Islands', 'iso2' => 'VI', 'iso3' => 'VIR', 'phone_prefix' => '1 340']);
        App\Country::create(['name' => 'Israel', 'english_name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'phone_prefix' => '972']);
        App\Country::create(['name' => 'Italia', 'english_name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'phone_prefix' => '39']);
        App\Country::create(['name' => 'Jamaica', 'english_name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'phone_prefix' => '1 876']);
        App\Country::create(['name' => 'Japón', 'english_name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'phone_prefix' => '81']);
        App\Country::create(['name' => 'Jersey', 'english_name' => 'Jersey', 'iso2' => 'JE', 'iso3' => 'JEY', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Jordania', 'english_name' => 'Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'phone_prefix' => '962']);
        App\Country::create(['name' => 'Kazajistán', 'english_name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'phone_prefix' => '7']);
        App\Country::create(['name' => 'Kenia', 'english_name' => 'Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'phone_prefix' => '254']);
        App\Country::create(['name' => 'Kirgizstán', 'english_name' => 'Kyrgyzstan', 'iso2' => 'KG', 'iso3' => 'KGZ', 'phone_prefix' => '996']);
        App\Country::create(['name' => 'Kiribati', 'english_name' => 'Kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'phone_prefix' => '686']);
        App\Country::create(['name' => 'Kuwait', 'english_name' => 'Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'phone_prefix' => '965']);
        App\Country::create(['name' => 'Líbano', 'english_name' => 'Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'phone_prefix' => '961']);
        App\Country::create(['name' => 'Laos', 'english_name' => 'Laos', 'iso2' => 'LA', 'iso3' => 'LAO', 'phone_prefix' => '856']);
        App\Country::create(['name' => 'Lesoto', 'english_name' => 'Lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'phone_prefix' => '266']);
        App\Country::create(['name' => 'Letonia', 'english_name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'phone_prefix' => '371']);
        App\Country::create(['name' => 'Liberia', 'english_name' => 'Liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'phone_prefix' => '231']);
        App\Country::create(['name' => 'Libia', 'english_name' => 'Libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'phone_prefix' => '218']);
        App\Country::create(['name' => 'Liechtenstein', 'english_name' => 'Liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'phone_prefix' => '423']);
        App\Country::create(['name' => 'Lituania', 'english_name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'phone_prefix' => '370']);
        App\Country::create(['name' => 'Luxemburgo', 'english_name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'phone_prefix' => '352']);
        App\Country::create(['name' => 'México', 'english_name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'phone_prefix' => '52']);
        App\Country::create(['name' => 'Mónaco', 'english_name' => 'Monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'phone_prefix' => '377']);
        App\Country::create(['name' => 'Macao', 'english_name' => 'Macao', 'iso2' => 'MO', 'iso3' => 'MAC', 'phone_prefix' => '853']);
        App\Country::create(['name' => 'Macedônia', 'english_name' => 'Macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'phone_prefix' => '389']);
        App\Country::create(['name' => 'Madagascar', 'english_name' => 'Madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'phone_prefix' => '261']);
        App\Country::create(['name' => 'Malasia', 'english_name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'phone_prefix' => '60']);
        App\Country::create(['name' => 'Malawi', 'english_name' => 'Malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'phone_prefix' => '265']);
        App\Country::create(['name' => 'Mali', 'english_name' => 'Mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'phone_prefix' => '223']);
        App\Country::create(['name' => 'Malta', 'english_name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'phone_prefix' => '356']);
        App\Country::create(['name' => 'Marruecos', 'english_name' => 'Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'phone_prefix' => '212']);
        App\Country::create(['name' => 'Martinica', 'english_name' => 'Martinique', 'iso2' => 'MQ', 'iso3' => 'MTQ', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Mauricio', 'english_name' => 'Mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'phone_prefix' => '230']);
        App\Country::create(['name' => 'Mauritania', 'english_name' => 'Mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'phone_prefix' => '222']);
        App\Country::create(['name' => 'Mayotte', 'english_name' => 'Mayotte', 'iso2' => 'YT', 'iso3' => 'MYT', 'phone_prefix' => '262']);
        App\Country::create(['name' => 'Micronesia', 'english_name' => 'Estados Federados de', 'iso2' => 'FM', 'iso3' => 'FSM', 'phone_prefix' => '691']);
        App\Country::create(['name' => 'Moldavia', 'english_name' => 'Moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'phone_prefix' => '373']);
        App\Country::create(['name' => 'Mongolia', 'english_name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'phone_prefix' => '976']);
        App\Country::create(['name' => 'Montenegro', 'english_name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'phone_prefix' => '382']);
        App\Country::create(['name' => 'Montserrat', 'english_name' => 'Montserrat', 'iso2' => 'MS', 'iso3' => 'MSR', 'phone_prefix' => '1 664']);
        App\Country::create(['name' => 'Mozambique', 'english_name' => 'Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'phone_prefix' => '258']);
        App\Country::create(['name' => 'Namibia', 'english_name' => 'Namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'phone_prefix' => '264']);
        App\Country::create(['name' => 'Nauru', 'english_name' => 'Nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'phone_prefix' => '674']);
        App\Country::create(['name' => 'Nepal', 'english_name' => 'Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'phone_prefix' => '977']);
        App\Country::create(['name' => 'Nicaragua', 'english_name' => 'Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'phone_prefix' => '505']);
        App\Country::create(['name' => 'Niger', 'english_name' => 'Niger', 'iso2' => 'NE', 'iso3' => 'NER', 'phone_prefix' => '227']);
        App\Country::create(['name' => 'Nigeria', 'english_name' => 'Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'phone_prefix' => '234']);
        App\Country::create(['name' => 'Niue', 'english_name' => 'Niue', 'iso2' => 'NU', 'iso3' => 'NIU', 'phone_prefix' => '683']);
        App\Country::create(['name' => 'Noruega', 'english_name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'phone_prefix' => '47']);
        App\Country::create(['name' => 'Nueva Caledonia', 'english_name' => 'New Caledonia', 'iso2' => 'NC', 'iso3' => 'NCL', 'phone_prefix' => '687']);
        App\Country::create(['name' => 'Nueva Zelanda', 'english_name' => 'New Zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'phone_prefix' => '64']);
        App\Country::create(['name' => 'Omán', 'english_name' => 'Oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'phone_prefix' => '968']);
        App\Country::create(['name' => 'Países Bajos', 'english_name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'phone_prefix' => '31']);
        App\Country::create(['name' => 'Pakistán', 'english_name' => 'Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'phone_prefix' => '92']);
        App\Country::create(['name' => 'Palau', 'english_name' => 'Palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'phone_prefix' => '680']);
        App\Country::create(['name' => 'Palestina', 'english_name' => 'Palestine', 'iso2' => 'PS', 'iso3' => 'PSE', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Panamá', 'english_name' => 'Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'phone_prefix' => '507']);
        App\Country::create(['name' => 'Papúa Nueva Guinea', 'english_name' => 'Papua New Guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'phone_prefix' => '675']);
        App\Country::create(['name' => 'Paraguay', 'english_name' => 'Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'phone_prefix' => '595']);
        App\Country::create(['name' => 'Perú', 'english_name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'phone_prefix' => '51']);
        App\Country::create(['name' => 'Polinesia Francesa', 'english_name' => 'French Polynesia', 'iso2' => 'PF', 'iso3' => 'PYF', 'phone_prefix' => '689']);
        App\Country::create(['name' => 'Polonia', 'english_name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'phone_prefix' => '48']);
        App\Country::create(['name' => 'Portugal', 'english_name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'phone_prefix' => '351']);
        App\Country::create(['name' => 'Puerto Rico', 'english_name' => 'Puerto Rico', 'iso2' => 'PR', 'iso3' => 'PRI', 'phone_prefix' => '1']);
        App\Country::create(['name' => 'Qatar', 'english_name' => 'Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'phone_prefix' => '974']);
        App\Country::create(['name' => 'Reino Unido', 'english_name' => 'United Kingdom', 'iso2' => 'GB', 'iso3' => 'GBR', 'phone_prefix' => '44']);
        App\Country::create(['name' => 'República Centroafricana', 'english_name' => 'Central African Republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'phone_prefix' => '236']);
        App\Country::create(['name' => 'República Checa', 'english_name' => 'Czech Republic', 'iso2' => 'CZ', 'iso3' => 'CZE', 'phone_prefix' => '420']);
        App\Country::create(['name' => 'República Dominicana', 'english_name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'phone_prefix' => '1 809']);
        App\Country::create(['name' => 'Reunión', 'english_name' => 'Réunion', 'iso2' => 'RE', 'iso3' => 'REU', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Ruanda', 'english_name' => 'Rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'phone_prefix' => '250']);
        App\Country::create(['name' => 'Rumanía', 'english_name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'phone_prefix' => '40']);
        App\Country::create(['name' => 'Rusia', 'english_name' => 'Russia', 'iso2' => 'RU', 'iso3' => 'RUS', 'phone_prefix' => '7']);
        App\Country::create(['name' => 'Sahara Occidental', 'english_name' => 'Western Sahara', 'iso2' => 'EH', 'iso3' => 'ESH', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Samoa', 'english_name' => 'Samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'phone_prefix' => '685']);
        App\Country::create(['name' => 'Samoa Americana', 'english_name' => 'American Samoa', 'iso2' => 'AS', 'iso3' => 'ASM', 'phone_prefix' => '1 684']);
        App\Country::create(['name' => 'San Bartolomé', 'english_name' => 'Saint Barthélemy', 'iso2' => 'BL', 'iso3' => 'BLM', 'phone_prefix' => '590']);
        App\Country::create(['name' => 'San Cristóbal y Nieves', 'english_name' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'phone_prefix' => '1 869']);
        App\Country::create(['name' => 'San Marino', 'english_name' => 'San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'phone_prefix' => '378']);
        App\Country::create(['name' => 'San Martín (Francia)', 'english_name' => 'Saint Martin (French part)', 'iso2' => 'MF', 'iso3' => 'MAF', 'phone_prefix' => '1 599']);
        App\Country::create(['name' => 'San Pedro y Miquelón', 'english_name' => 'Saint Pierre and Miquelon', 'iso2' => 'PM', 'iso3' => 'SPM', 'phone_prefix' => '508']);
        App\Country::create(['name' => 'San Vicente y las Granadinas', 'english_name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'phone_prefix' => '1 784']);
        App\Country::create(['name' => 'Santa Elena', 'english_name' => 'Ascensión y Tristán de Acuña', 'iso2' => 'SH', 'iso3' => 'SHN', 'phone_prefix' => '290']);
        App\Country::create(['name' => 'Santa Lucía', 'english_name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'phone_prefix' => '1 758']);
        App\Country::create(['name' => 'Santo Tomé y Príncipe', 'english_name' => 'Sao Tome and Principe', 'iso2' => 'ST', 'iso3' => 'STP', 'phone_prefix' => '239']);
        App\Country::create(['name' => 'Senegal', 'english_name' => 'Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'phone_prefix' => '221']);
        App\Country::create(['name' => 'Serbia', 'english_name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'phone_prefix' => '381']);
        App\Country::create(['name' => 'Seychelles', 'english_name' => 'Seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'phone_prefix' => '248']);
        App\Country::create(['name' => 'Sierra Leona', 'english_name' => 'Sierra Leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'phone_prefix' => '232']);
        App\Country::create(['name' => 'Singapur', 'english_name' => 'Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'phone_prefix' => '65']);
        App\Country::create(['name' => 'Siria', 'english_name' => 'Syria', 'iso2' => 'SY', 'iso3' => 'SYR', 'phone_prefix' => '963']);
        App\Country::create(['name' => 'Somalia', 'english_name' => 'Somalia', 'iso2' => 'SO', 'iso3' => 'SOM', 'phone_prefix' => '252']);
        App\Country::create(['name' => 'Sri lanka', 'english_name' => 'Sri Lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'phone_prefix' => '94']);
        App\Country::create(['name' => 'Sudáfrica', 'english_name' => 'South Africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'phone_prefix' => '27']);
        App\Country::create(['name' => 'Sudán', 'english_name' => 'Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'phone_prefix' => '249']);
        App\Country::create(['name' => 'Suecia', 'english_name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'phone_prefix' => '46']);
        App\Country::create(['name' => 'Suiza', 'english_name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'phone_prefix' => '41']);
        App\Country::create(['name' => 'Surinám', 'english_name' => 'Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'phone_prefix' => '597']);
        App\Country::create(['name' => 'Svalbard y Jan Mayen', 'english_name' => 'Svalbard and Jan Mayen', 'iso2' => 'SJ', 'iso3' => 'SJM', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Swazilandia', 'english_name' => 'Swaziland', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'phone_prefix' => '268']);
        App\Country::create(['name' => 'Tadjikistán', 'english_name' => 'Tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'phone_prefix' => '992']);
        App\Country::create(['name' => 'Tailandia', 'english_name' => 'Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'phone_prefix' => '66']);
        App\Country::create(['name' => 'Taiwán', 'english_name' => 'Taiwan', 'iso2' => 'TW', 'iso3' => 'TWN', 'phone_prefix' => '886']);
        App\Country::create(['name' => 'Tanzania', 'english_name' => 'Tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'phone_prefix' => '255']);
        App\Country::create(['name' => 'Territorio Británico del Océano Índico', 'english_name' => 'British Indian Ocean Territory', 'iso2' => 'IO', 'iso3' => 'IOT', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Territorios Australes y Antárticas Franceses', 'english_name' => 'French Southern Territories', 'iso2' => 'TF', 'iso3' => 'ATF', 'phone_prefix' => '']);
        App\Country::create(['name' => 'Timor Oriental', 'english_name' => 'East Timor', 'iso2' => 'TL', 'iso3' => 'TLS', 'phone_prefix' => '670']);
        App\Country::create(['name' => 'Togo', 'english_name' => 'Togo', 'iso2' => 'TG', 'iso3' => 'TGO', 'phone_prefix' => '228']);
        App\Country::create(['name' => 'Tokelau', 'english_name' => 'Tokelau', 'iso2' => 'TK', 'iso3' => 'TKL', 'phone_prefix' => '690']);
        App\Country::create(['name' => 'Tonga', 'english_name' => 'Tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'phone_prefix' => '676']);
        App\Country::create(['name' => 'Trinidad y Tobago', 'english_name' => 'Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'phone_prefix' => '1 868']);
        App\Country::create(['name' => 'Tunez', 'english_name' => 'Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'phone_prefix' => '216']);
        App\Country::create(['name' => 'Turkmenistán', 'english_name' => 'Turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'phone_prefix' => '993']);
        App\Country::create(['name' => 'Turquía', 'english_name' => 'Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'phone_prefix' => '90']);
        App\Country::create(['name' => 'Tuvalu', 'english_name' => 'Tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'phone_prefix' => '688']);
        App\Country::create(['name' => 'Ucrania', 'english_name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'phone_prefix' => '380']);
        App\Country::create(['name' => 'Uganda', 'english_name' => 'Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'phone_prefix' => '256']);
        App\Country::create(['name' => 'Uruguay', 'english_name' => 'Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'phone_prefix' => '598']);
        App\Country::create(['name' => 'Uzbekistán', 'english_name' => 'Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'phone_prefix' => '998']);
        App\Country::create(['name' => 'Vanuatu', 'english_name' => 'Vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'phone_prefix' => '678']);
        App\Country::create(['name' => 'Venezuela', 'english_name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'phone_prefix' => '58']);
        App\Country::create(['name' => 'Vietnam', 'english_name' => 'Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'phone_prefix' => '84']);
        App\Country::create(['name' => 'Wallis y Futuna', 'english_name' => 'Wallis and Futuna', 'iso2' => 'WF', 'iso3' => 'WLF', 'phone_prefix' => '681']);
        App\Country::create(['name' => 'Yemen', 'english_name' => 'Yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'phone_prefix' => '967']);
        App\Country::create(['name' => 'Yibuti', 'english_name' => 'Djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'phone_prefix' => '253']);
        App\Country::create(['name' => 'Zambia', 'english_name' => 'Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'phone_prefix' => '260']);
        App\Country::create(['name' => 'Zimbabue', 'english_name' => 'Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'phone_prefix' => '263']);        
    }
}
